#
# Run repoman via travis
# See https://github.com/mrueg/repoman-travis
#
language: python
services: docker
arch:
    - amd64
os: linux
dist: bionic
branches:
    only:
        - master
python:
    - "3.8"
env:
    jobs:
        - PORTAGE_VER="3.0.7"
before_install:
    - sudo apt-get -qq update
    - pip install lxml pyyaml
before_script:
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /var /var/cache
    - mkdir -p travis-overlay /etc/portage /var/cache/distfiles /var/db/repos/gentoo
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    - mv .travis travis-overlay/
    - wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/spinner.sh"
    - wget -qO - "https://github.com/gentoo/portage/archive/portage-${PORTAGE_VER}.tar.gz" | tar xz
    - wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | tar xz -C /var/db/repos/gentoo --strip-components=1
    - chmod a+rwx spinner.sh
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
    - ln -s $TRAVIS_BUILD_DIR/portage-portage-${PORTAGE_VER}/cnf/repos.conf /etc/portage/repos.conf
    - ln -s /var/db/repos/gentoo/profiles/default/linux/amd64/17.0 /etc/portage/make.profile
    - cd travis-overlay
script:
    - .travis/travis_ci.sh
